@startuml

title Class diagram

class Conveyor {
    Command[] commands
    void power_on()
}

class Command {
  CommandState state
  void execute()
  void revert()
  bool can_retry_execute
  bool can_retry_revert
  bool failed_on_revert_is_fatal
}

enum CommandState {
    New
    Done
    Reverted
    Error
    ErrorOnRevert
}

class ConveyorError {
}

class ConveyorFatalError{
}

class CommandError{
    Exception inner_exception
}

Exception <|-- ConveyorError
Exception <|-- ConveyorFatalError
Exception <|-- CommandError


@enduml